"""Dialect-aware JSONB.

Prefer real JSONB on Postgres (indexable, typed operators) but fall back to
``JSON`` on SQLite so the in-memory test harness still works. Autogenerated
migrations still emit ``postgresql.JSONB`` because we only run migrations
against Postgres.
"""

from __future__ import annotations

from typing import Any

from sqlalchemy import JSON, types
from sqlalchemy.dialects.postgresql import JSONB as PgJSONB
from sqlalchemy.engine import Dialect


class JSONB(types.TypeDecorator[Any]):
    impl = JSON
    cache_ok = True

    def load_dialect_impl(self, dialect: Dialect) -> Any:
        if dialect.name == "postgresql":
            return dialect.type_descriptor(PgJSONB())
        return dialect.type_descriptor(JSON())
