"""initial schema

Revision ID: a7023fe9dcf1
Revises: 0000_baseline
Create Date: 2026-04-18 07:12:45.719497+00:00

"""
from __future__ import annotations

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'a7023fe9dcf1'
down_revision: Union[str, None] = '0000_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('github_login', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_table('installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_installation_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installations_github_installation_id'), 'installations', ['github_installation_id'], unique=True)
    op.create_index(op.f('ix_installations_user_id'), 'installations', ['user_id'], unique=False)
    op.create_table('user_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('encrypted_key', sa.LargeBinary(), nullable=False),
    sa.Column('masked_hint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider')
    )
    op.create_index(op.f('ix_user_api_keys_user_id'), 'user_api_keys', ['user_id'], unique=False)
    op.create_table('repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('primary_language', sa.String(length=64), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indexing_status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repos_full_name'), 'repos', ['full_name'], unique=False)
    op.create_index(op.f('ix_repos_github_repo_id'), 'repos', ['github_repo_id'], unique=True)
    op.create_index(op.f('ix_repos_installation_id'), 'repos', ['installation_id'], unique=False)
    op.create_table('code_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'file_path', 'start_line', name='uq_chunk_location')
    )
    op.create_index(op.f('ix_code_chunks_content_hash'), 'code_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_code_chunks_repo_id'), 'code_chunks', ['repo_id'], unique=False)
    op.create_table('issue_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body_excerpt', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'issue_number', name='uq_issue_embedding')
    )
    op.create_index(op.f('ix_issue_embeddings_repo_id'), 'issue_embeddings', ['repo_id'], unique=False)
    op.create_table('repo_configs',
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('monthly_budget_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tone', sa.String(length=32), nullable=False),
    sa.Column('enabled_steps_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auto_actions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('label_map_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reproduce_languages_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('repo_id')
    )
    op.create_table('triage_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('duplicates_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reproduction_verdict', sa.String(length=32), nullable=True),
    sa.Column('reproduction_log', sa.Text(), nullable=True),
    sa.Column('suspected_files_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('draft_comment', sa.Text(), nullable=True),
    sa.Column('proposed_labels_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('proposed_action', sa.String(length=48), nullable=True),
    sa.Column('budget_limited', sa.Boolean(), nullable=False),
    sa.Column('raw_payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('final_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'issue_number', name='uq_repo_issue')
    )
    op.create_index(op.f('ix_triage_cards_repo_id'), 'triage_cards', ['repo_id'], unique=False)
    op.create_index(op.f('ix_triage_cards_status'), 'triage_cards', ['status'], unique=False)
    op.create_table('llm_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('step_name', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['triage_cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_created_at'), 'llm_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_usage_repo_id'), 'llm_usage', ['repo_id'], unique=False)

    # pgvector ivfflat indexes — cosine distance, lists=100. Good enough for
    # small-to-mid repos; tune per-repo in phase 6 if needed.
    op.execute(
        "CREATE INDEX ix_code_chunks_embedding ON code_chunks "
        "USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"
    )
    op.execute(
        "CREATE INDEX ix_issue_embeddings_embedding ON issue_embeddings "
        "USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_issue_embeddings_embedding")
    op.execute("DROP INDEX IF EXISTS ix_code_chunks_embedding")
    op.drop_index(op.f('ix_llm_usage_repo_id'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_created_at'), table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_index(op.f('ix_triage_cards_status'), table_name='triage_cards')
    op.drop_index(op.f('ix_triage_cards_repo_id'), table_name='triage_cards')
    op.drop_table('triage_cards')
    op.drop_table('repo_configs')
    op.drop_index(op.f('ix_issue_embeddings_repo_id'), table_name='issue_embeddings')
    op.drop_table('issue_embeddings')
    op.drop_index(op.f('ix_code_chunks_repo_id'), table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_content_hash'), table_name='code_chunks')
    op.drop_table('code_chunks')
    op.drop_index(op.f('ix_repos_installation_id'), table_name='repos')
    op.drop_index(op.f('ix_repos_github_repo_id'), table_name='repos')
    op.drop_index(op.f('ix_repos_full_name'), table_name='repos')
    op.drop_table('repos')
    op.drop_index(op.f('ix_user_api_keys_user_id'), table_name='user_api_keys')
    op.drop_table('user_api_keys')
    op.drop_index(op.f('ix_installations_user_id'), table_name='installations')
    op.drop_index(op.f('ix_installations_github_installation_id'), table_name='installations')
    op.drop_table('installations')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
