"use client";

import Link from "next/link";
import { useState } from "react";
import {
  AlertTriangle,
  Check,
  ExternalLink,
  Github,
  Inbox,
  KeyRound,
  RefreshCw,
  RotateCcw,
  Webhook,
} from "lucide-react";

import { AppShell, EmptyState, PageHeader, Skeleton } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { ApiError } from "@/lib/api";
import {
  type AppDetails,
  type HydrateResult,
  type InstallationOut,
  type Repo,
  useAppDetails,
  useBackfillRepo,
  useDeleteApp,
  useHydrateRepos,
  useInstallations,
  useMe,
  useRepos,
} from "@/lib/hooks";

export default function GithubSettingsPage() {
  const me = useMe();
  const signedIn = Boolean(me.data);
  const details = useAppDetails(signedIn);
  const installations = useInstallations(signedIn);
  const deleteApp = useDeleteApp();
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [error, setError] = useState<string | null>(null);

  return (
    <AppShell me={me.data ?? null}>
      {!signedIn ? (
        <EmptyState
          icon={Github}
          title="Sign in to view GitHub configuration"
          description="This page shows the registered App, stored secrets (masked), and installations attached to your account."
        />
      ) : (
        <>
          <PageHeader
            title="GitHub configuration"
            description="Every value bugsift stored during onboarding. Secrets are masked — bugsift never displays them in plaintext."
          />

          {details.isLoading || !details.data ? (
            <Skeleton className="h-64 w-full" />
          ) : !details.data.configured ? (
            <NotConfigured />
          ) : (
            <div className="space-y-6">
              <AppSection details={details.data} />
              <TunnelSection details={details.data} />
              <InstallationsSection
                loading={installations.isLoading}
                installations={installations.data ?? []}
                appSlug={details.data.slug ?? null}
              />
              <ReposSection signedIn={signedIn} />
              <DangerZone
                details={details.data}
                confirming={confirmDelete}
                onToggle={() => {
                  setError(null);
                  setConfirmDelete((v) => !v);
                }}
                onConfirm={async () => {
                  try {
                    await deleteApp.mutateAsync();
                    setConfirmDelete(false);
                    window.location.assign("/onboarding?step=app");
                  } catch (e) {
                    if (e instanceof ApiError) setError(e.message);
                    else if (e instanceof Error) setError(e.message);
                    else setError("failed to remove App");
                  }
                }}
                pending={deleteApp.isPending}
                error={error}
              />
            </div>
          )}
        </>
      )}
    </AppShell>
  );
}

function NotConfigured() {
  return (
    <EmptyState
      icon={Github}
      title="No GitHub App configured yet"
      description="Run the onboarding wizard to register the App in one click. Everything you'd normally set up manually on github.com (App ID, client secret, private key, webhook secret, permissions, events, callbacks) is automated."
      action={
        <Link
          href="/onboarding?step=app"
          className="inline-flex h-10 items-center gap-1 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground hover:bg-primary/90"
        >
          Start onboarding
        </Link>
      }
    />
  );
}

function AppSection({ details }: { details: AppDetails }) {
  return (
    <section className="rounded-lg border bg-card p-6 shadow-sm">
      <div className="mb-1 flex items-center gap-2">
        <Github className="h-4 w-4 text-muted-foreground" />
        <h2 className="text-base font-medium">Registered App</h2>
      </div>
      <p className="text-sm text-muted-foreground">
        These values were generated by GitHub when you clicked &ldquo;Create
        App&rdquo;. They&apos;re stored encrypted at rest.
      </p>

      <dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2">
        <Field label="Name" value={details.name} />
        <Field label="Owner" value={details.owner_login} />
        <Field label="App ID" value={details.github_app_id?.toString() ?? null} mono />
        <Field label="Slug" value={details.slug} mono />
        <Field label="Client ID" value={details.client_id} mono />
        <Field
          label="Client secret"
          value={details.client_secret_masked}
          mono
          hint="Masked — bugsift never returns the plaintext."
        />
        <Field
          label="Webhook secret"
          value={details.webhook_secret_masked}
          mono
          hint="Masked — used to verify GitHub webhook signatures."
        />
        <Field
          label="Private key fingerprint"
          value={details.private_key_fingerprint}
          mono
          hint="SHA-256 of the stored PEM. Compare with GitHub's App page to verify."
        />
        <Field
          label="Created"
          value={details.created_at ? new Date(details.created_at).toLocaleString() : null}
        />
        <Field
          label="Last updated"
          value={details.updated_at ? new Date(details.updated_at).toLocaleString() : null}
        />
      </dl>

      {details.html_url && (
        <div className="mt-5 flex flex-wrap gap-3">
          <a
            href={details.html_url}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex h-9 items-center gap-1.5 rounded-md border border-input bg-background px-3 text-sm font-medium hover:bg-accent hover:text-accent-foreground"
          >
            View on GitHub <ExternalLink className="h-3.5 w-3.5" />
          </a>
          <a
            href={`${details.html_url}/advanced`}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex h-9 items-center gap-1.5 rounded-md border border-input bg-background px-3 text-sm font-medium hover:bg-accent hover:text-accent-foreground"
          >
            Recent webhook deliveries <ExternalLink className="h-3.5 w-3.5" />
          </a>
        </div>
      )}
    </section>
  );
}

function TunnelSection({ details }: { details: AppDetails }) {
  return (
    <section className="rounded-lg border bg-card p-6 shadow-sm">
      <div className="mb-1 flex items-center gap-2">
        <Webhook className="h-4 w-4 text-muted-foreground" />
        <h2 className="text-base font-medium">Webhook tunnel</h2>
      </div>
      <p className="text-sm text-muted-foreground">
        GitHub can&apos;t reach <code>localhost</code>. bugsift auto-provisions
        a free smee.io channel and runs an in-process forwarder that relays
        events to the webhook route. No terminal process required.
      </p>

      <dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2">
        <Field
          label="Tunnel URL"
          value={details.tunnel_url}
          mono
          hint="The URL GitHub POSTs to."
        />
        <div>
          <dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
            Forwarder
          </dt>
          <dd className="mt-1 flex items-center gap-2">
            {details.tunnel_running ? (
              <span className="inline-flex items-center gap-1.5 rounded-full border border-green-600/40 bg-green-600/10 px-2 py-0.5 text-xs font-medium text-green-700">
                <Check className="h-3 w-3" />
                running
              </span>
            ) : (
              <span className="inline-flex items-center gap-1.5 rounded-full border border-amber-500/40 bg-amber-500/10 px-2 py-0.5 text-xs font-medium text-amber-700">
                <AlertTriangle className="h-3 w-3" />
                stopped
              </span>
            )}
          </dd>
        </div>
      </dl>
    </section>
  );
}

function InstallationsSection({
  loading,
  installations,
  appSlug,
}: {
  loading: boolean;
  installations: InstallationOut[];
  appSlug: string | null;
}) {
  const installUrl = appSlug
    ? `https://github.com/apps/${appSlug}/installations/new`
    : null;
  const hydrate = useHydrateRepos();
  const [hydrateMessage, setHydrateMessage] = useState<string | null>(null);
  const [hydrateError, setHydrateError] = useState<string | null>(null);

  return (
    <section className="rounded-lg border bg-card p-6 shadow-sm">
      <div className="mb-1 flex items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <KeyRound className="h-4 w-4 text-muted-foreground" />
          <h2 className="text-base font-medium">Installations</h2>
        </div>
        <div className="flex gap-2">
          <button
            type="button"
            onClick={async () => {
              setHydrateMessage(null);
              setHydrateError(null);
              try {
                const result: HydrateResult = await hydrate.mutateAsync();
                setHydrateMessage(
                  `Re-synced ${result.installations} installation${
                    result.installations === 1 ? "" : "s"
                  } — ${result.added} new repo${result.added === 1 ? "" : "s"}, ${result.skipped} already present.`,
                );
              } catch (e) {
                setHydrateError(
                  e instanceof ApiError
                    ? e.message
                    : e instanceof Error
                      ? e.message
                      : "hydrate failed",
                );
              }
            }}
            disabled={hydrate.isPending}
            className="inline-flex h-8 items-center gap-1.5 rounded-md border border-input bg-background px-3 text-xs font-medium hover:bg-accent hover:text-accent-foreground disabled:opacity-50"
          >
            {hydrate.isPending ? "syncing…" : "Re-sync repos"}
          </button>
          {installUrl && (
            <a
              href={installUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex h-8 items-center gap-1.5 rounded-md border border-input bg-background px-3 text-xs font-medium hover:bg-accent hover:text-accent-foreground"
            >
              Install on another repo <ExternalLink className="h-3 w-3" />
            </a>
          )}
        </div>
      </div>
      <p className="text-sm text-muted-foreground">
        Each installation binds bugsift to a repo you own or maintain. Use
        <strong> Re-sync repos</strong> if GitHub&apos;s install webhook
        arrived without its repo list (a known GitHub quirk) — bugsift will
        query the API and backfill.
      </p>
      {hydrateMessage && (
        <p className="mt-2 rounded-md border border-primary/30 bg-primary/5 px-3 py-1.5 text-xs text-primary">
          {hydrateMessage}
        </p>
      )}
      {hydrateError && (
        <p className="mt-2 rounded-md border border-destructive/30 bg-destructive/5 px-3 py-1.5 text-xs text-destructive">
          {hydrateError}
        </p>
      )}

      {loading ? (
        <Skeleton className="mt-4 h-16 w-full" />
      ) : installations.length === 0 ? (
        <p className="mt-4 text-sm text-muted-foreground">
          No installations yet. Install the App on a repo to start triaging.
        </p>
      ) : (
        <ul className="mt-4 divide-y">
          {installations.map((inst) => (
            <li key={inst.id} className="flex items-center justify-between py-3 text-sm">
              <div>
                <div className="font-mono text-xs text-muted-foreground">
                  installation #{inst.github_installation_id}
                </div>
                <div className="mt-0.5">
                  {inst.repo_count} repo{inst.repo_count === 1 ? "" : "s"} · installed{" "}
                  {new Date(inst.installed_at).toLocaleDateString()}
                  {inst.suspended_at && (
                    <span className="ml-2 rounded-full border border-amber-500/40 bg-amber-500/10 px-2 py-0.5 text-xs font-medium text-amber-700">
                      suspended
                    </span>
                  )}
                </div>
              </div>
              {appSlug && (
                <a
                  href={`https://github.com/settings/installations/${inst.github_installation_id}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-xs underline underline-offset-4"
                >
                  Manage on GitHub
                </a>
              )}
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}

function ReposSection({ signedIn }: { signedIn: boolean }) {
  const repos = useRepos(signedIn);
  const backfill = useBackfillRepo();
  const [status, setStatus] = useState<{
    repoId: number;
    kind: "ok" | "err";
    message: string;
  } | null>(null);

  return (
    <section className="rounded-lg border bg-card p-6 shadow-sm">
      <div className="mb-1 flex items-center gap-2">
        <Inbox className="h-4 w-4 text-muted-foreground" />
        <h2 className="text-base font-medium">Synced repos</h2>
      </div>
      <p className="text-sm text-muted-foreground">
        When bugsift adds a repo, it automatically pulls every open issue and
        runs them through triage so the dashboard reflects the current state.
        Use <strong>Triage existing issues</strong> to re-run that pass on
        demand &mdash; useful if a repo was attached before the App config was
        finalised, or to pick up issues opened while the tunnel was offline.
      </p>

      {repos.isLoading ? (
        <Skeleton className="mt-4 h-16 w-full" />
      ) : (repos.data ?? []).length === 0 ? (
        <p className="mt-4 text-sm text-muted-foreground">
          No repos synced yet. Install the App on a repo, or click{" "}
          <em>Re-sync repos</em> above if an install event arrived empty.
        </p>
      ) : (
        <ul className="mt-4 divide-y">
          {(repos.data ?? []).map((repo: Repo) => (
            <li
              key={repo.id}
              className="flex items-center justify-between gap-4 py-3 text-sm"
            >
              <div className="min-w-0">
                <div className="truncate font-medium">{repo.full_name}</div>
                <div className="mt-0.5 text-xs text-muted-foreground">
                  {repo.primary_language ?? "unknown language"} ·{" "}
                  {repo.default_branch} · indexing:{" "}
                  <span className="font-mono">{repo.indexing_status}</span>
                </div>
                {status?.repoId === repo.id && (
                  <div
                    className={
                      "mt-1 text-xs " +
                      (status.kind === "ok"
                        ? "text-primary"
                        : "text-destructive")
                    }
                  >
                    {status.message}
                  </div>
                )}
              </div>
              <button
                type="button"
                onClick={async () => {
                  setStatus(null);
                  try {
                    await backfill.mutateAsync(repo.id);
                    setStatus({
                      repoId: repo.id,
                      kind: "ok",
                      message:
                        "Queued. Existing open issues will appear in the Queue as triage completes.",
                    });
                  } catch (e) {
                    setStatus({
                      repoId: repo.id,
                      kind: "err",
                      message:
                        e instanceof ApiError
                          ? e.message
                          : e instanceof Error
                            ? e.message
                            : "backfill failed",
                    });
                  }
                }}
                disabled={backfill.isPending}
                className="shrink-0 inline-flex h-8 items-center gap-1.5 rounded-md border border-input bg-background px-3 text-xs font-medium hover:bg-accent hover:text-accent-foreground disabled:opacity-50"
              >
                {backfill.isPending && backfill.variables === repo.id
                  ? "queueing…"
                  : "Triage existing issues"}
              </button>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}

function DangerZone({
  details,
  confirming,
  onToggle,
  onConfirm,
  pending,
  error,
}: {
  details: AppDetails;
  confirming: boolean;
  onToggle: () => void;
  onConfirm: () => void;
  pending: boolean;
  error: string | null;
}) {
  return (
    <section className="rounded-lg border border-destructive/30 bg-destructive/5 p-6">
      <div className="mb-1 flex items-center gap-2">
        <RotateCcw className="h-4 w-4 text-destructive" />
        <h2 className="text-base font-medium text-destructive">
          Re-register the App
        </h2>
      </div>
      <p className="text-sm text-muted-foreground">
        Removes the stored credentials (App ID, client secret, webhook secret,
        private key) and starts the onboarding wizard. Your existing App on
        github.com is <strong>not</strong> deleted &mdash; you can either install
        the new App side-by-side, or delete the old one from{" "}
        {details.html_url ? (
          <a
            href={`${details.html_url}/advanced`}
            target="_blank"
            rel="noopener noreferrer"
            className="underline underline-offset-4"
          >
            its GitHub settings
          </a>
        ) : (
          "its GitHub settings"
        )}
        . Installations already linked will stop receiving events.
      </p>

      {confirming ? (
        <div className="mt-4 space-y-3 rounded-md border border-destructive/30 bg-background/60 p-4 text-sm">
          <div className="font-medium">Confirm removal</div>
          <div className="text-muted-foreground">
            This will wipe the App credentials from bugsift and send you to
            onboarding Step 1. Continue?
          </div>
          {error && (
            <div className="rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-destructive">
              {error}
            </div>
          )}
          <div className="flex gap-2">
            <Button
              size="sm"
              variant="destructive"
              onClick={onConfirm}
              disabled={pending}
            >
              {pending ? "removing…" : "Yes, remove App"}
            </Button>
            <Button size="sm" variant="outline" onClick={onToggle}>
              Cancel
            </Button>
          </div>
        </div>
      ) : (
        <div className="mt-4">
          <Button variant="outline" onClick={onToggle}>
            <RefreshCw className="mr-2 h-4 w-4" />
            Remove and re-register
          </Button>
        </div>
      )}
    </section>
  );
}

function Field({
  label,
  value,
  mono = false,
  hint,
}: {
  label: string;
  value: string | null | undefined;
  mono?: boolean;
  hint?: string;
}) {
  return (
    <div>
      <dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
        {label}
      </dt>
      <dd className={"mt-1 " + (mono ? "font-mono text-xs break-all" : "text-sm")}>
        {value || <span className="text-muted-foreground">—</span>}
      </dd>
      {hint && <p className="mt-1 text-xs text-muted-foreground">{hint}</p>}
    </div>
  );
}
